name: TD_M2
channels:
  - conda-forge
  - fredboudon
  - defaults
dependencies:
  - python #=3.7.8
  - alinea.caribu
  - openalea.lpy=3.7
  - openalea.mtg
  #- openalea.plantgl
  #- pyopengl=3.1.1a1=py37_0
